#!/usr/bin/env sh
# ------------------------------------------------------------------------------
exec parallel --line-buffer ::: \
  'jekyll serve -tw' \
  'sass --watch css/style.sass:css/style.css' \
  "$@"